.catalog:
  version: "v0.0.1"
  questions:
    - variable: "DOCKER_BRIDGE"
      label: "Docker Bridge"
      description: "Name of Docker Bridge. Default is `docker0`"
      type: "string"
      default: "mpbr0"
      required: true
    - variable: MTU
      label: "MTU for the network"
      description: "Adjust the MTU for the network, according to your needs. Ex: GCE(1460), AWS(1500), etc"
      required: true
      default: 1500
      type: int
    - variable: "SUBNET"
      label: "Subnet"
      description: "The subnet to use for the managed network."
      type: "string"
      default: '192.168.100.0/24'
      required: true
    - variable: "STARTADDR"
      label: "IP Pool Start Address"
      description: "The start address of the IP pool."
      type: "string"
      default: '192.168.100.2'
      required: true
    - variable: "ENDADDR"
      label: "Subnet"
      description: "The end address of the IP pool."
      type: "string"
      default: '192.168.100.100'
      required: true
    - variable: "GATEWAY"
      label: "Gateway"
      description: "Container default gateway."
      type: "string"
      default: '192.168.100.1'
      required: true
    - variable: "NIC_ON_BRIDGE"
      label: "Interface card name on the bridge."
      description: "The interface card name which it will attach into the bridge."
      type: "string"
      default: 'eth1'
      required: true
    - variable: "RANCHER_DEBUG"
      label: "Enable Debug Logs"
      description: "This will enable very verbose debug logs."
      type: "boolean"
      default: "true"
      required: true

flat:
  network_driver:
    name: Rancher Flat Networking
    default_network:
      name: flat
      host_ports: true
      subnets:
      - network_address: $SUBNET
      - start_address: $STARTADDR
      - end_address: $ENDADDR
      dns:
      - 169.254.169.250
      dns_search:
      - rancher.internal
    cni_config:
      '10-rancher-flat.conf':
        name: rancher-cni-network
        type: rancher-bridge
        bridge: $DOCKER_BRIDGE
        bridgeSubnet: $SUBNET
        logToFile: /var/log/rancher-cni.log
        isDebugLevel: ${RANCHER_DEBUG}
        hairpinMode: true
        hostNat: true
        hairpinMode: true
        mtu: ${MTU}
        linkMTUOverhead: 50
        isDefaultGateway: true
        ipam:
          type: rancher-cni-ipam
          logToFile: /var/log/rancher-cni.log
          isDebugLevel: ${RANCHER_DEBUG}
          gateway: ${GATEWAY}
          routes:
            - dst: 169.254.169.250/32
              gw: 172.22.101.103
